<?php
$pageTitle = 'Competition 2026';
require_once __DIR__ . '/includes/header.php';
$tournament = active_tournament($pdo);
if (!$tournament) { echo '<main class="container empty"><i class="fa-solid fa-trophy"></i><h2>Belum ada turnamen</h2></main>'; require __DIR__.'/includes/footer.php'; exit; }
$tid=(int)$tournament['id'];
$participantCount=$pdo->prepare('SELECT COUNT(*) FROM participants WHERE tournament_id=? AND status="active"');$participantCount->execute([$tid]);$participantCount=(int)$participantCount->fetchColumn();
$stats=tournament_stats($pdo,$tid);$progress=$stats['total']?(int)round($stats['finished']/$stats['total']*100):0;
$live=$pdo->prepare("SELECT m.*,p1.name p1_name,p2.name p2_name FROM matches m LEFT JOIN participants p1 ON p1.id=m.participant1_id LEFT JOIN participants p2 ON p2.id=m.participant2_id WHERE m.tournament_id=? AND m.status='live' ORDER BY m.started_at DESC LIMIT 2");$live->execute([$tid]);$liveMatches=$live->fetchAll();
$upcoming=$pdo->prepare("SELECT m.*,p1.name p1_name,p2.name p2_name FROM matches m LEFT JOIN participants p1 ON p1.id=m.participant1_id LEFT JOIN participants p2 ON p2.id=m.participant2_id WHERE m.tournament_id=? AND m.status='scheduled' ORDER BY m.scheduled_at LIMIT 3");$upcoming->execute([$tid]);
$results=$pdo->prepare("SELECT m.*,p1.name p1_name,p2.name p2_name FROM matches m LEFT JOIN participants p1 ON p1.id=m.participant1_id LEFT JOIN participants p2 ON p2.id=m.participant2_id WHERE m.tournament_id=? AND m.status='finished' ORDER BY m.finished_at DESC LIMIT 3");$results->execute([$tid]);
?>
<main>
<section class="hero"><div class="container"><div class="eyebrow">Official Tournament Series</div><h1><?= e(strtoupper($tournament['name'])) ?> <span><?= date('Y',strtotime($tournament['start_date'])) ?></span></h1><p class="hero-subtitle">Official Tournament &amp; Live Scoring System</p><div class="hero-meta"><div class="meta-item"><i class="fa-regular fa-calendar"></i><?= date('d M',strtotime($tournament['start_date'])) ?>–<?= date('d M Y',strtotime($tournament['end_date'])) ?></div><div class="meta-item"><i class="fa-solid fa-location-dot"></i><?= e($tournament['location']) ?></div><div class="meta-item"><i class="fa-solid fa-users"></i><?= $participantCount ?> Participants</div><div class="meta-item"><i class="fa-solid fa-gamepad"></i><?= (int)$stats['total'] ?> Matches</div><span class="badge <?= e($tournament['status']) ?>"><?= e($tournament['status']) ?></span></div><div class="actions"><a class="btn btn-primary" href="bracket.php"><i class="fa-solid fa-sitemap"></i>VIEW BRACKET</a><a class="btn btn-ghost" href="matches.php?status=live"><i class="fa-solid fa-bolt"></i>LIVE MATCHES</a></div></div></section>

<?php if($liveMatches): ?><section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Happening now</div><h2>Live matches</h2></div></div><div class="grid grid-2" id="live-match-grid"><?php foreach($liveMatches as $m): ?><a class="card match-card" href="match.php?id=<?=$m['id']?>"><div class="match-card-head"><span class="round-label"><?=e($m['round'])?></span><span class="badge live">Live</span></div><div class="team-line"><span class="team"><span class="team-logo"><?=strtoupper(substr($m['p1_name']??'T',0,1))?></span><?=e($m['p1_name']??'TBD')?></span><span class="score"><?=$m['score1']?></span></div><div class="team-line"><span class="team"><span class="team-logo"><?=strtoupper(substr($m['p2_name']??'T',0,1))?></span><?=e($m['p2_name']??'TBD')?></span><span class="score"><?=$m['score2']?></span></div><div class="match-card-foot"><span><?=e($m['court'])?></span><span>Open scoreboard <i class="fa-solid fa-arrow-right"></i></span></div></a><?php endforeach;?></div></div></section><?php endif; ?>

<section class="section"><div class="container"><div class="grid grid-3"><div class="card progress-card"><div class="eyebrow">Tournament progress</div><div class="progress-row"><strong><?=$progress?>%</strong><span><?= (int)$stats['finished'] ?> / <?= (int)$stats['total'] ?> completed</span></div><div class="progress-track"><div class="progress-fill" style="width:<?=$progress?>%"></div></div><small>Every result updates the bracket automatically.</small></div><div class="card" style="grid-column:span 2"><div class="section-head"><div><div class="eyebrow">Next on court</div><h2>Upcoming matches</h2></div><a href="matches.php">View all</a></div><?php foreach($upcoming->fetchAll() as $m):?><a class="participant-rank" href="match.php?id=<?=$m['id']?>"><span class="team-logo"><i class="fa-solid fa-bolt"></i></span><span class="detail"><strong><?=e($m['p1_name']??'TBD')?> vs <?=e($m['p2_name']??'TBD')?></strong><small><?=e($m['round'])?> · <?=e($m['court'])?></small></span><time><?= $m['scheduled_at']?date('d M, H:i',strtotime($m['scheduled_at'])):'TBA'?></time></a><?php endforeach;?></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Confirmed scores</div><h2>Latest results</h2></div><a href="results.php">All results</a></div><div class="grid grid-3"><?php $resultRows=$results->fetchAll(); if(!$resultRows):?><div class="card empty"><i class="fa-solid fa-flag-checkered"></i><p>No completed matches yet.</p></div><?php endif; foreach($resultRows as $m):?><a class="card match-card" href="match.php?id=<?=$m['id']?>"><div class="match-card-head"><span class="round-label"><?=e($m['round'])?></span><span class="badge finished">Finished</span></div><div class="team-line"><span><?=e($m['p1_name'])?></span><strong class="score"><?=$m['score1']?></strong></div><div class="team-line"><span><?=e($m['p2_name'])?></span><strong class="score"><?=$m['score2']?></strong></div></a><?php endforeach;?></div></div></section>
</main>
<script>setInterval(async()=>{try{const r=await fetch(`${APP_BASE}/api/get_matches.php?status=live`);const j=await r.json();if(j.success&&j.data.length&&document.querySelector('#live-match-grid'))j.data.slice(0,2).forEach((m,i)=>{const c=document.querySelectorAll('#live-match-grid .match-card')[i];if(c){c.querySelectorAll('.score')[0].textContent=m.score1;c.querySelectorAll('.score')[1].textContent=m.score2}})}catch(e){}},3000)</script>
<?php require __DIR__ . '/includes/footer.php'; ?>

